version: '2'
services:
  nginx:
    image: nginx:latest
    command: nginx -g 'daemon off;'
    volumes:
      - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8083:80"
  php-7.1-fpm:
      #build: ./php-7.1-fpm
      image: bitnami/php-fpm:latest
      ports:
        - "9011:9000"
      volumes:
        - ./www:/var/www/html
  jenkins:
#    image: jenkins/jenkins:latest
    build: ./jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./www:/var/project_www
      - ./origin:/var/project_origin
  gitlabs:
    image: gitlab/gitlab-ce:latest
    ports:
      - "8443:443"
      - "8082:80"
    volumes:
      - ./gitlab-ce/config:/etc/gitlab:Z
      - ./gitlab-ce/logs:/var/log/gitlab:Z
      - ./gitlab-ce/data:/var/opt/gitlab:Z
    links:
      - jenkins
